server:
  port: 8081
spring:
  application:
    name: user-service
  aop:
    auto: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://47.103.70.243:3306/shop?useUnicode=true&characterEncoding=utf8&useSSL=false

mybatis:
  type-aliases-package: cn.wy.user.entity
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    jdbc-type-for-null: null
    map-underscore-to-camel-case: false

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka